#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "matterbridge"
name = "Matterbridge"
description.en = "Multi-protocols bridge for online communications"
description.fr = "Connecteur entre une série de protocoles de discussion"

version = "1.26.0~ynh2"

maintainers = []

[upstream]
license = "Apache-2.0"
admindoc = "https://github.com/42wim/matterbridge/wiki"
code = "https://github.com/42wim/matterbridge"

[integration]
yunohost = ">= 11.0.9"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "60M"
ram.build = "50M"
ram.runtime = "50M"

[install]

[resources]
    [resources.sources.main]
    in_subdir = false
    amd64.url = "https://github.com/42wim/matterbridge/releases/download/v1.26.0/matterbridge-1.26.0-linux-64bit"
    amd64.sha256 = "7f5a74b9b7cbf395b8873f3f3f418d90c61197e3cc677882e70b7faeef4c35b0"
    arm64.url = "https://github.com/42wim/matterbridge/releases/download/v1.26.0/matterbridge-1.26.0-linux-arm64"
    arm64.sha256 = "3d922187ce3e792f9cf896e209c828d3466e3b2453f3a133f7f610f9d6937587"
    armhf.url = "https://github.com/42wim/matterbridge/releases/download/v1.26.0/matterbridge-1.26.0-linux-armv6"
    armhf.sha256 = "fee25dc50c96508147c88c0da05c6143681f8c88bdbef1c42a91bf9388aa13f9"

    extract = false
    rename = "matterbridge"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "matterbridge-.*-linux-64bit"
    autoupdate.asset.arm64 = "matterbridge-.*-linux-arm64"
    autoupdate.asset.armhf = "matterbridge-.*-linux-armv6"

    [resources.system_user]

    [resources.install_dir]
