#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"
chmod +x "$install_dir/matterbridge"

#=================================================
# MODIFY A CONFIG FILE
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="matterbridge.toml" --destination="$install_dir/matterbridge.toml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Multi-protocols bridge for online communications" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
